### ISSUE TITLE
Not Working in IE

### ISSUE THREAD

**Issue by sudan92hard** [chromawoods/instaFilta#11]
The js is not getting loaded in IE browser even after setting the javascript setting as enabled

**Comment by chromawoods** [comment]
Please be more specific. Code example perhaps?
1. What version of IE? 
2. Where are you loading the script; header, footer?
3. Have you included jQuery before the instaFilta script?

**Comment by sudan92hard** [comment]
1. In IE 9
2. The script is loaded in the header
3. Yes

This is the start of my file:
html
head
script src="./js/jquery-2.1.1.min.js"
script src="./js/instafilta.min.js"
script src="./js/handlebars.js"
script src="./js/app.js"
And a console.log() stmt in my app.js on document.ready() is not getting executed

**Comment by chromawoods** [comment]
I just tested the plugin successfully in a native IE8 on Win XP. Seems to work just fine. There is probably something else in your architecture that is causing this.

...since your issue was created a long time ago, I'm sure you have already fixed it yourself. Adding this comment for the record. If I don't hear from you in a week or so, I will close this issue.
